#!/bin/bash

(( $# != 1 )) && { echo "Usage: $0 [output]">&2; exit 1; } 

winid="$(xdotool selectwindow)"

read position size < <(xdotool getwindowgeometry "$winid" | sed -En 's/\s*(Geometry|Position): (\S+)\s*.*/\2/p' | xargs)

IFS=x read x y <<<"$size" 
x=$((x- (x % 2)))
y=$((y- (y % 2)))


ffmpeg -video_size "${x}x${y}" -framerate 60 -f x11grab -i :0.0+"$position" -c:v libx264 -profile:v baseline -level 3.0 "$1" #-pix_fmt yuv420p "$1"
